services:
  - type: web
    name: discovergroup-api
    env: node
    plan: free
    buildCommand: node scripts/build-api-deploy.js
    startCommand: cd dist-node/apps/api && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main
    rootDir: ./
    healthCheckPath: /health