[build]
  base = "apps/admin"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://discovergroup.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200